language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5

# before_script:
# - sudo bash utils/test_setup.sh

install:
- pip install virtualenv tox coveralls

script:
- python setup.py test
- python setup.py check -r

after_success:
- coveralls
